name: Deploy Flask App to GCP

on:
  workflow_dispatch:  # manual trigger 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GCP VM via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true
          sudo docker rmi flask-app || true
          rm -rf containerized-flask-cicd
          git clone https://github.com/${{ github.repository }}.git containerized-flask-cicd
          cd containerized-flask-cicd
          sudo docker build -t flask-app .
          sudo docker run -d -p 5000:5000 --name flask-app flask-app
